"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { DEFAULT_USER_PROFILE, saveUserProfile } from "@/lib/storage";

const interests = ["Travel", "Music", "Tech", "Fitness", "Art", "Coffee", "Cooking", "Reading", "Movies", "Gaming"];

export default function OnboardingPage() {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [profile, setProfile] = useState(DEFAULT_USER_PROFILE);
  const patch = (value: Partial<typeof profile>) => setProfile((current) => ({ ...current, ...value }));
  const toggle = (interest: string) => patch({ interests: profile.interests.includes(interest) ? profile.interests.filter((item) => item !== interest) : [...profile.interests, interest] });
  const submit = (event: FormEvent) => { event.preventDefault(); saveUserProfile(profile); router.push("/discover"); };
  const steps = [
    <div key="basics" className="space-y-4"><h2 className="text-2xl font-bold">Let&apos;s start with you</h2><p className="text-white/50">A few details help us find better connections.</p><input value={profile.name} onChange={(e) => patch({ name: e.target.value })} placeholder="Your name" className="w-full h-14 rounded-2xl bg-white/5 border border-white/10 px-4 outline-none focus:border-[#ff4458]" required /><input type="number" min="18" max="99" value={profile.age} onChange={(e) => patch({ age: Number(e.target.value) })} placeholder="Age" className="w-full h-14 rounded-2xl bg-white/5 border border-white/10 px-4 outline-none focus:border-[#ff4458]" required /><input value={profile.location} onChange={(e) => patch({ location: e.target.value })} placeholder="City" className="w-full h-14 rounded-2xl bg-white/5 border border-white/10 px-4 outline-none focus:border-[#ff4458]" required /></div>,
    <div key="goal" className="space-y-4"><h2 className="text-2xl font-bold">What are you looking for?</h2>{["Something meaningful", "Long-term relationship", "Something casual", "Still figuring it out"].map((goal) => <button type="button" key={goal} onClick={() => patch({ datingGoal: goal })} className={`w-full p-4 rounded-2xl text-left border ${profile.datingGoal === goal ? "border-[#ff4458] bg-[#ff4458]/15" : "border-white/10 bg-white/5"}`}>{goal}</button>)}</div>,
    <div key="interests" className="space-y-4"><h2 className="text-2xl font-bold">Show your personality</h2><p className="text-white/50">Choose at least three interests.</p><div className="flex flex-wrap gap-2">{interests.map((interest) => <button type="button" key={interest} onClick={() => toggle(interest)} className={`px-4 py-3 rounded-full border text-sm ${profile.interests.includes(interest) ? "bg-[#ff4458] border-[#ff4458]" : "bg-white/5 border-white/10 text-white/60"}`}>{profile.interests.includes(interest) && <Check className="inline w-4 h-4 mr-1" />}{interest}</button>)}</div></div>,
    <div key="preferences" className="space-y-5"><h2 className="text-2xl font-bold">Set your preferences</h2><label className="block text-sm text-white/60">Age range<div className="flex items-center gap-3 mt-2"><input type="number" min="18" value={profile.minAge} onChange={(e) => patch({ minAge: Number(e.target.value) })} className="w-full h-12 rounded-xl bg-white/5 border border-white/10 px-3" /><span>to</span><input type="number" max="99" value={profile.maxAge} onChange={(e) => patch({ maxAge: Number(e.target.value) })} className="w-full h-12 rounded-xl bg-white/5 border border-white/10 px-3" /></div></label><label className="block text-sm text-white/60">Maximum distance: <span className="text-white">{profile.maxDistance} km</span><input type="range" min="1" max="100" value={profile.maxDistance} onChange={(e) => patch({ maxDistance: Number(e.target.value) })} className="mt-4 w-full accent-[#ff4458]" /></label></div>,
  ];
  return <main className="min-h-screen bg-[#0f0f12] max-w-lg mx-auto px-5 py-6"><header className="flex items-center justify-between"><button onClick={() => step > 0 ? setStep(step - 1) : router.back()} className="w-10 h-10 rounded-full bg-white/5 flex items-center justify-center" aria-label="Go back"><ArrowLeft className="w-5 h-5" /></button><span className="text-sm text-white/50">{step + 1} of {steps.length}</span><div className="w-10" /></header><div className="mt-8 flex gap-1">{steps.map((_, index) => <div key={index} className={`h-1 flex-1 rounded-full ${index <= step ? "bg-[#ff4458]" : "bg-white/10"}`} />)}</div><form onSubmit={submit} className="mt-14">{steps[step]}<button type={step === steps.length - 1 ? "submit" : "button"} onClick={() => step < steps.length - 1 && setStep(step + 1)} disabled={step === 2 && profile.interests.length < 3} className="mt-10 w-full h-14 rounded-2xl bg-[#ff4458] font-semibold disabled:opacity-40 flex items-center justify-center gap-2">{step === steps.length - 1 ? "Finish profile" : "Continue"}<ArrowRight className="w-5 h-5" /></button></form></main>;
}
